@echo off
cd /d "c:\Users\ysk144\.gemini\antigravity\playground\harmonic-prominence"
echo Starting AI Blog Master...
echo Opening Browser...
start http://localhost:3000/blog
echo Starting Server...
npm run dev
pause
